// Code generated by "stringer -type ExifField"; DO NOT EDIT.

package img

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Title-0]
	_ = x[Source-1]
	_ = x[Byline-2]
	_ = x[Credit-3]
	_ = x[Rights-4]
	_ = x[Copyright-5]
	_ = x[Caption-6]
	_ = x[UserComment-7]
	_ = x[Description-8]
	_ = x[Notes-9]
	_ = x[ImageDescription-10]
	_ = x[CatalogSets-11]
	_ = x[HierarchicalSubject-12]
	_ = x[LastKeywordXMP-13]
	_ = x[Subject-14]
	_ = x[Keywords-15]
	_ = x[Categories-16]
	_ = x[TagsList-17]
	_ = x[ImageHeight-18]
	_ = x[ImageWidth-19]
	_ = x[MIMEType-20]
	_ = x[FileTypeExtension-21]
	_ = x[WebP_Flags-22]
	_ = x[Duration-23]
	_ = x[FileName-24]
	_ = x[SourceFile-25]
}

const _ExifField_name = "TitleSourceBylineCreditRightsCopyrightCaptionUserCommentDescriptionNotesImageDescriptionCatalogSetsHierarchicalSubjectLastKeywordXMPSubjectKeywordsCategoriesTagsListImageHeightImageWidthMIMETypeFileTypeExtensionWebP_FlagsDurationFileNameSourceFile"

var _ExifField_index = [...]uint8{0, 5, 11, 17, 23, 29, 38, 45, 56, 67, 72, 88, 99, 118, 132, 139, 147, 157, 165, 176, 186, 194, 211, 221, 229, 237, 247}

func (i ExifField) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExifField_index)-1 {
		return "ExifField(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExifField_name[_ExifField_index[idx]:_ExifField_index[idx+1]]
}
